import { Product, Collection, Review, Category, ShippingOption } from "@/types";

export const COLLECTIONS: Collection[] = [
  {
    id: "1",
    name: "Bridal Couture",
    slug: "bridal-couture",
    description: "Exquisite bridal wear for your special day",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCZgQemWTJYcNGbQ1CLiUieXl88zu7SuUFGzsf5Gv-aNQWfwjf3C2dp_sh7LAldJT9SN7y1vEA-Wa43JxqvubIBkZYKYpXGERXs3qbHsYGEbC9IStdlrJ8dRcJXLMHC8xcgKfdXfoxl1i-l_ZPvav9_A_c-YCm2efOSDOvUxjLn9oIe1Y-3d9fEgDMPbWDqfsCJ4jS0-a1uQaP1WVvmarV_7ZPp3EulU_gVdgG6uDEvYlFRvGG_nsfiwd0zlNe9Obu1dg8s9Tj0Htc",
    productCount: 24,
  },
  {
    id: "2",
    name: "Pret-a-Porter",
    slug: "pret-a-porter",
    description: "Ready to wear elegance for every occasion",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAxGLiOQm0E1GKAkXRnvT3wwhbpd-EuejhaKWTDvgO8lzcHkrw7ilNXEhk2Vh6pTgaTxNIaFGI5bpbK3PJ2JuyKWtyWirvTafF6eKeF2YIquW_rIuTYbLjNteYEqB-5QVgfaNjM1-Ly_eHIHk5Y3H7bxlLB4Byk7STc1-MXkSRolC2tkXCXlsv8hefcLHeqwfoTNcrbJCff_fyj53hmp87NTIqzQ-EAYp1CE2z5BVX-ug3ThGs67MYNBilE7elUGHZPNKw_0YLZI9k",
    productCount: 45,
  },
  {
    id: "3",
    name: "Luxury Unstitched",
    slug: "luxury-unstitched",
    description: "Premium fabrics for custom creations",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCN9sRxqEiEvfwUQz8K5WQ5OqfKfAdQaCeIWGTs9F34YA9tJhoMO7AB1abw23UDdHPJxYDB7Yt6Fl7CLJmlFkbpDqEjtm7XlJU2VqF324iUpbQVZQ4arxZzFKwTy9qShyj244Zx1sZBTgOKr79rqwacA22f7PemYZDqexnH-l3JJ9nqiFnIILn-sJrMzKvw2VlnerE4KN9dhhnJX8iudPY1GjY5L3GA-r0djmfdxmZBGib0jrGTeN0pNVBveXoegpXmSAUk1GqwJvI",
    productCount: 32,
  },
];

export const CATEGORIES: Category[] = [
  { id: "1", name: "New Arrivals", slug: "new-arrivals", productCount: 18 },
  { id: "2", name: "Unstitched", slug: "unstitched", productCount: 32 },
  { id: "3", name: "Pret", slug: "pret", productCount: 45 },
  { id: "4", name: "Ready to Wear", slug: "ready-to-wear", productCount: 28 },
  { id: "5", name: "Luxury Pret", slug: "luxury-pret", productCount: 15 },
  { id: "6", name: "Formals", slug: "formals", productCount: 22 },
  { id: "7", name: "Sale", slug: "sale", productCount: 12 },
];

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Emerald Silk Tunic",
    slug: "emerald-silk-tunic",
    description: "A stunning emerald green silk tunic featuring intricate hand-embroidered details and delicate sequin work. Perfect for formal gatherings and festive occasions. The shirt is crafted from pure crinkle chiffon with a modern cut that flatters all body types.",
    price: 12500,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAxGLiOQm0E1GKAkXRnvT3wwhbpd-EuejhaKWTDvgO8lzcHkrw7ilNXEhk2Vh6pTgaTxNIaFGI5bpbK3PJ2JuyKWtyWirvTafF6eKeF2YIquW_rIuTYbLjNteYEqB-5QVgfaNjM1-Ly_eHIHk5Y3H7bxlLB4Byk7STc1-MXkSRolC2tkXCXlsv8hefcLHeqwfoTNcrbJCff_fyj53hmp87NTIqzQ-EAYp1CE2z5BVX-ug3ThGs67MYNBilE7elUGHZPNKw_0YLZI9k",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCZgQemWTJYcNGbQ1CLiUieXl88zu7SuUFGzsf5Gv-aNQWfwjf3C2dp_sh7LAldJT9SN7y1vEA-Wa43JxqvubIBkZYKYpXGERXs3qbHsYGEbC9IStdlrJ8dRcJXLMHC8xcgKfdXfoxl1i-l_ZPvav9_A_c-YCm2efOSDOvUxjLn9oIe1Y-3d9fEgDMPbWDqfsCJ4jS0-a1uQaP1WVvmarV_7ZPp3EulU_gVdgG6uDEvYlFRvGG_nsfiwd0zlNe9Obu1dg8s9Tj0Htc",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCN9sRxqEiEvfwUQz8K5WQ5OqfKfAdQaCeIWGTs9F34YA9tJhoMO7AB1abw23UDdHPJxYDB7Yt6Fl7CLJmlFkbpDqEjtm7XlJU2VqF324iUpbQVZQ4arxZzFKwTy9qShyj244Zx1sZBTgOKr79rqwacA22f7PemYZDqexnH-l3JJ9nqiFnIILn-sJrMzKvw2VlnerE4KN9dhhnJX8iudPY1GjY5L3GA-r0djmfdxmZBGib0jrGTeN0pNVBveXoegpXmSAUk1GqwJvI",
    ],
    category: "Formal Wear",
    categorySlug: "formals",
    collection: "Festive Edit",
    fabric: "Pure Silk",
    colors: [
      { name: "Emerald", hex: "#2D5F2D" },
      { name: "Navy", hex: "#1E3A5F" },
    ],
    sizes: [
      { name: "XS", available: true },
      { name: "S", available: true },
      { name: "M", available: true },
      { name: "L", available: true },
      { name: "XL", available: false },
    ],
    stock: 15,
    isNew: true,
    rating: 4.8,
    reviewCount: 124,
    features: ["Hand-embroidered details", "Pure silk fabric", "Modern cut"],
    modelInfo: "Model is 5'7\" wearing size S",
  },
  {
    id: "2",
    name: "Ivory Chiffon Set",
    slug: "ivory-chiffon-set",
    description: "A timeless ivory ensemble featuring intricate thread work and delicate sequin embellishments. The shirt is crafted from pure crinkle chiffon, paired with raw silk trousers and a heavily embroidered chiffon dupatta.",
    price: 18900,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCZgQemWTJYcNGbQ1CLiUieXl88zu7SuUFGzsf5Gv-aNQWfwjf3C2dp_sh7LAldJT9SN7y1vEA-Wa43JxqvubIBkZYKYpXGERXs3qbHsYGEbC9IStdlrJ8dRcJXLMHC8xcgKfdXfoxl1i-l_ZPvav9_A_c-YCm2efOSDOvUxjLn9oIe1Y-3d9fEgDMPbWDqfsCJ4jS0-a1uQaP1WVvmarV_7ZPp3EulU_gVdgG6uDEvYlFRvGG_nsfiwd0zlNe9Obu1dg8s9Tj0Htc",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAxGLiOQm0E1GKAkXRnvT3wwhbpd-EuejhaKWTDvgO8lzcHkrw7ilNXEhk2Vh6pTgaTxNIaFGI5bpbK3PJ2JuyKWtyWirvTafF6eKeF2YIquW_rIuTYbLjNteYEqB-5QVgfaNjM1-Ly_eHIHk5Y3H7bxlLB4Byk7STc1-MXkSRolC2tkXCXlsv8hefcLHeqwfoTNcrbJCff_fyj53hmp87NTIqzQ-EAYp1CE2z5BVX-ug3ThGs67MYNBilE7elUGHZPNKw_0YLZI9k",
    ],
    category: "Luxury Pret",
    categorySlug: "luxury-pret",
    collection: "Noor Collection",
    fabric: "Pure Crinkle Chiffon",
    colors: [
      { name: "Ivory Pearl", hex: "#FFFFF0" },
      { name: "Blush Pink", hex: "#FFB6C1" },
      { name: "Sage", hex: "#9DC183" },
    ],
    sizes: [
      { name: "XS", available: true },
      { name: "S", available: true },
      { name: "M", available: true },
      { name: "L", available: false },
      { name: "XL", available: true },
    ],
    stock: 3,
    isNew: true,
    rating: 4.9,
    reviewCount: 89,
    features: ["Pure Crinkle Chiffon", "3-Piece Stitched Suit", "Hand-embroidered details"],
    modelInfo: "Model is 5'7\" wearing size S",
  },
  {
    id: "3",
    name: "Royal Velvet Shawl",
    slug: "royal-velvet-shawl",
    description: "Luxurious velvet shawl with intricate gold embroidery, perfect for winter weddings and formal events.",
    price: 8500,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCN9sRxqEiEvfwUQz8K5WQ5OqfKfAdQaCeIWGTs9F34YA9tJhoMO7AB1abw23UDdHPJxYDB7Yt6Fl7CLJmlFkbpDqEjtm7XlJU2VqF324iUpbQVZQ4arxZzFKwTy9qShyj244Zx1sZBTgOKr79rqwacA22f7PemYZDqexnH-l3JJ9nqiFnIILn-sJrMzKvw2VlnerE4KN9dhhnJX8iudPY1GjY5L3GA-r0djmfdxmZBGib0jrGTeN0pNVBveXoegpXmSAUk1GqwJvI",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCZgQemWTJYcNGbQ1CLiUieXl88zu7SuUFGzsf5Gv-aNQWfwjf3C2dp_sh7LAldJT9SN7y1vEA-Wa43JxqvubIBkZYKYpXGERXs3qbHsYGEbC9IStdlrJ8dRcJXLMHC8xcgKfdXfoxl1i-l_ZPvav9_A_c-YCm2efOSDOvUxjLn9oIe1Y-3d9fEgDMPbWDqfsCJ4jS0-a1uQaP1WVvmarV_7ZPp3EulU_gVdgG6uDEvYlFRvGG_nsfiwd0zlNe9Obu1dg8s9Tj0Htc",
    ],
    category: "Accessories",
    categorySlug: "accessories",
    fabric: "Velvet",
    colors: [
      { name: "Maroon", hex: "#800000" },
      { name: "Navy", hex: "#1E3A5F" },
      { name: "Emerald", hex: "#2D5F2D" },
    ],
    sizes: [
      { name: "One Size", available: true },
    ],
    stock: 25,
    rating: 4.7,
    reviewCount: 56,
    features: ["Premium velvet", "Gold embroidery", "Versatile styling"],
  },
  {
    id: "4",
    name: "Noir Gold Evening",
    slug: "noir-gold-evening",
    description: "A sophisticated black evening ensemble adorned with intricate gold threadwork. Features a flowing silhouette perfect for formal dinners and evening events.",
    price: 24000,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAxGLiOQm0E1GKAkXRnvT3wwhbpd-EuejhaKWTDvgO8lzcHkrw7ilNXEhk2Vh6pTgaTxNIaFGI5bpbK3PJ2JuyKWtyWirvTafF6eKeF2YIquW_rIuTYbLjNteYEqB-5QVgfaNjM1-Ly_eHIHk5Y3H7bxlLB4Byk7STc1-MXkSRolC2tkXCXlsv8hefcLHeqwfoTNcrbJCff_fyj53hmp87NTIqzQ-EAYp1CE2z5BVX-ug3ThGs67MYNBilE7elUGHZPNKw_0YLZI9k",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCN9sRxqEiEvfwUQz8K5WQ5OqfKfAdQaCeIWGTs9F34YA9tJhoMO7AB1abw23UDdHPJxYDB7Yt6Fl7CLJmlFkbpDqEjtm7XlJU2VqF324iUpbQVZQ4arxZzFKwTy9qShyj244Zx1sZBTgOKr79rqwacA22f7PemYZDqexnH-l3JJ9nqiFnIILn-sJrMzKvw2VlnerE4KN9dhhnJX8iudPY1GjY5L3GA-r0djmfdxmZBGib0jrGTeN0pNVBveXoegpXmSAUk1GqwJvI",
    ],
    category: "Bridal Series",
    categorySlug: "bridal-couture",
    collection: "Evening Edit",
    fabric: "Organza",
    colors: [
      { name: "Black Gold", hex: "#1A1A1A" },
    ],
    sizes: [
      { name: "XS", available: true },
      { name: "S", available: true },
      { name: "M", available: true },
      { name: "L", available: true },
      { name: "XL", available: true },
    ],
    stock: 8,
    rating: 4.9,
    reviewCount: 45,
    features: ["Hand-crafted gold work", "Premium organza", "Flowing silhouette"],
    modelInfo: "Model is 5'6\" wearing size M",
  },
  {
    id: "5",
    name: "Emerald Velvet Set",
    slug: "emerald-velvet-set",
    description: "A luxurious velvet ensemble in rich emerald green, featuring intricate gold embroidery and modern silhouette.",
    price: 18500,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCN9sRxqEiEvfwUQz8K5WQ5OqfKfAdQaCeIWGTs9F34YA9tJhoMO7AB1abw23UDdHPJxYDB7Yt6Fl7CLJmlFkbpDqEjtm7XlJU2VqF324iUpbQVZQ4arxZzFKwTy9qShyj244Zx1sZBTgOKr79rqwacA22f7PemYZDqexnH-l3JJ9nqiFnIILn-sJrMzKvw2VlnerE4KN9dhhnJX8iudPY1GjY5L3GA-r0djmfdxmZBGib0jrGTeN0pNVBveXoegpXmSAUk1GqwJvI",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAxGLiOQm0E1GKAkXRnvT3wwhbpd-EuejhaKWTDvgO8lzcHkrw7ilNXEhk2Vh6pTgaTxNIaFGI5bpbK3PJ2JuyKWtyWirvTafF6eKeF2YIquW_rIuTYbLjNteYEqB-5QVgfaNjM1-Ly_eHIHk5Y3H7bxlLB4Byk7STc1-MXkSRolC2tkXCXlsv8hefcLHeqwfoTNcrbJCff_fyj53hmp87NTIqzQ-EAYp1CE2z5BVX-ug3ThGs67MYNBilE7elUGHZPNKw_0YLZI9k",
    ],
    category: "Festive Edit",
    categorySlug: "formals",
    collection: "Heritage & Harmony",
    fabric: "Velvet",
    colors: [
      { name: "Emerald", hex: "#2D5F2D" },
      { name: "Burgundy", hex: "#722F37" },
    ],
    sizes: [
      { name: "XS", available: false },
      { name: "S", available: true },
      { name: "M", available: true },
      { name: "L", available: true },
      { name: "XL", available: false },
    ],
    stock: 12,
    isNew: true,
    rating: 4.8,
    reviewCount: 67,
    features: ["Premium velvet", "Gold embroidery", "3-piece set"],
    modelInfo: "Model is 5'7\" wearing size S",
  },
  {
    id: "6",
    name: "Ivory Chiffon Kalidaar",
    slug: "ivory-chiffon-kalidaar",
    description: "Elegant ivory chiffon kalidaar with delicate embroidery, perfect for daytime events and celebrations.",
    price: 12500,
    originalPrice: 15500,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCZgQemWTJYcNGbQ1CLiUieXl88zu7SuUFGzsf5Gv-aNQWfwjf3C2dp_sh7LAldJT9SN7y1vEA-Wa43JxqvubIBkZYKYpXGERXs3qbHsYGEbC9IStdlrJ8dRcJXLMHC8xcgKfdXfoxl1i-l_ZPvav9_A_c-YCm2efOSDOvUxjLn9oIe1Y-3d9fEgDMPbWDqfsCJ4jS0-a1uQaP1WVvmarV_7ZPp3EulU_gVdgG6uDEvYlFRvGG_nsfiwd0zlNe9Obu1dg8s9Tj0Htc",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAxGLiOQm0E1GKAkXRnvT3wwhbpd-EuejhaKWTDvgO8lzcHkrw7ilNXEhk2Vh6pTgaTxNIaFGI5bpbK3PJ2JuyKWtyWirvTafF6eKeF2YIquW_rIuTYbLjNteYEqB-5QVgfaNjM1-Ly_eHIHk5Y3H7bxlLB4Byk7STc1-MXkSRolC2tkXCXlsv8hefcLHeqwfoTNcrbJCff_fyj53hmp87NTIqzQ-EAYp1CE2z5BVX-ug3ThGs67MYNBilE7elUGHZPNKw_0YLZI9k",
    ],
    category: "Pret",
    categorySlug: "pret",
    fabric: "Chiffon",
    colors: [
      { name: "Ivory", hex: "#FFFFF0" },
    ],
    sizes: [
      { name: "XS", available: true },
      { name: "S", available: true },
      { name: "M", available: true },
      { name: "L", available: true },
      { name: "XL", available: true },
    ],
    stock: 20,
    isSale: true,
    rating: 4.6,
    reviewCount: 98,
    features: ["Lightweight chiffon", "Delicate embroidery", "Comfortable fit"],
  },
  {
    id: "7",
    name: "Maroon Heritage Suit",
    slug: "maroon-heritage-suit",
    description: "A stunning maroon suit inspired by traditional Pakistani craftsmanship with modern design elements.",
    price: 22000,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAxGLiOQm0E1GKAkXRnvT3wwhbpd-EuejhaKWTDvgO8lzcHkrw7ilNXEhk2Vh6pTgaTxNIaFGI5bpbK3PJ2JuyKWtyWirvTafF6eKeF2YIquW_rIuTYbLjNteYEqB-5QVgfaNjM1-Ly_eHIHk5Y3H7bxlLB4Byk7STc1-MXkSRolC2tkXCXlsv8hefcLHeqwfoTNcrbJCff_fyj53hmp87NTIqzQ-EAYp1CE2z5BVX-ug3ThGs67MYNBilE7elUGHZPNKw_0YLZI9k",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCN9sRxqEiEvfwUQz8K5WQ5OqfKfAdQaCeIWGTs9F34YA9tJhoMO7AB1abw23UDdHPJxYDB7Yt6Fl7CLJmlFkbpDqEjtm7XlJU2VqF324iUpbQVZQ4arxZzFKwTy9qShyj244Zx1sZBTgOKr79rqwacA22f7PemYZDqexnH-l3JJ9nqiFnIILn-sJrMzKvw2VlnerE4KN9dhhnJX8iudPY1GjY5L3GA-r0djmfdxmZBGib0jrGTeN0pNVBveXoegpXmSAUk1GqwJvI",
    ],
    category: "Heritage Collection",
    categorySlug: "formals",
    collection: "Heritage & Harmony",
    fabric: "Silk",
    colors: [
      { name: "Maroon", hex: "#800000" },
      { name: "Gold", hex: "#FFD700" },
    ],
    sizes: [
      { name: "XS", available: true },
      { name: "S", available: true },
      { name: "M", available: true },
      { name: "L", available: false },
      { name: "XL", available: false },
    ],
    stock: 6,
    rating: 4.9,
    reviewCount: 34,
    features: ["Pure silk", "Traditional embroidery", "Heritage inspired"],
    modelInfo: "Model is 5'6\" wearing size S",
  },
  {
    id: "8",
    name: "Noir Silk Kurta",
    slug: "noir-silk-kurta",
    description: "Classic black silk kurta with subtle gold accents, perfect for evening gatherings.",
    price: 9500,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCN9sRxqEiEvfwUQz8K5WQ5OqfKfAdQaCeIWGTs9F34YA9tJhoMO7AB1abw23UDdHPJxYDB7Yt6Fl7CLJmlFkbpDqEjtm7XlJU2VqF324iUpbQVZQ4arxZzFKwTy9qShyj244Zx1sZBTgOKr79rqwacA22f7PemYZDqexnH-l3JJ9nqiFnIILn-sJrMzKvw2VlnerE4KN9dhhnJX8iudPY1GjY5L3GA-r0djmfdxmZBGib0jrGTeN0pNVBveXoegpXmSAUk1GqwJvI",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCZgQemWTJYcNGbQ1CLiUieXl88zu7SuUFGzsf5Gv-aNQWfwjf3C2dp_sh7LAldJT9SN7y1vEA-Wa43JxqvubIBkZYKYpXGERXs3qbHsYGEbC9IStdlrJ8dRcJXLMHC8xcgKfdXfoxl1i-l_ZPvav9_A_c-YCm2efOSDOvUxjLn9oIe1Y-3d9fEgDMPbWDqfsCJ4jS0-a1uQaP1WVvmarV_7ZPp3EulU_gVdgG6uDEvYlFRvGG_nsfiwd0zlNe9Obu1dg8s9Tj0Htc",
    ],
    category: "Pret",
    categorySlug: "pret",
    fabric: "Silk",
    colors: [
      { name: "Black", hex: "#1A1A1A" },
    ],
    sizes: [
      { name: "XS", available: true },
      { name: "S", available: true },
      { name: "M", available: true },
      { name: "L", available: true },
      { name: "XL", available: true },
    ],
    stock: 30,
    isTrending: true,
    rating: 4.7,
    reviewCount: 156,
    features: ["Pure silk", "Minimal design", "Versatile"],
  },
  {
    id: "9",
    name: "Blush Organza Wrap",
    slug: "blush-organza-wrap",
    description: "Delicate blush pink organza wrap with pearl embellishments, ideal for formal occasions.",
    price: 14000,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCZgQemWTJYcNGbQ1CLiUieXl88zu7SuUFGzsf5Gv-aNQWfwjf3C2dp_sh7LAldJT9SN7y1vEA-Wa43JxqvubIBkZYKYpXGERXs3qbHsYGEbC9IStdlrJ8dRcJXLMHC8xcgKfdXfoxl1i-l_ZPvav9_A_c-YCm2efOSDOvUxjLn9oIe1Y-3d9fEgDMPbWDqfsCJ4jS0-a1uQaP1WVvmarV_7ZPp3EulU_gVdgG6uDEvYlFRvGG_nsfiwd0zlNe9Obu1dg8s9Tj0Htc",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAxGLiOQm0E1GKAkXRnvT3wwhbpd-EuejhaKWTDvgO8lzcHkrw7ilNXEhk2Vh6pTgaTxNIaFGI5bpbK3PJ2JuyKWtyWirvTafF6eKeF2YIquW_rIuTYbLjNteYEqB-5QVgfaNjM1-Ly_eHIHk5Y3H7bxlLB4Byk7STc1-MXkSRolC2tkXCXlsv8hefcLHeqwfoTNcrbJCff_fyj53hmp87NTIqzQ-EAYp1CE2z5BVX-ug3ThGs67MYNBilE7elUGHZPNKw_0YLZI9k",
    ],
    category: "Formals",
    categorySlug: "formals",
    fabric: "Organza",
    colors: [
      { name: "Blush", hex: "#FFB6C1" },
      { name: "Sage", hex: "#9DC183" },
    ],
    sizes: [
      { name: "XS", available: true },
      { name: "S", available: true },
      { name: "M", available: true },
      { name: "L", available: true },
      { name: "XL", available: false },
    ],
    stock: 15,
    rating: 4.8,
    reviewCount: 72,
    features: ["Premium organza", "Pearl embellishments", "Elegant draping"],
    modelInfo: "Model is 5'7\" wearing size S",
  },
  {
    id: "10",
    name: "Royal Gold Ensemble",
    slug: "royal-gold-ensemble",
    description: "A majestic gold and blue ensemble perfect for weddings and grand celebrations.",
    price: 28000,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCN9sRxqEiEvfwUQz8K5WQ5OqfKfAdQaCeIWGTs9F34YA9tJhoMO7AB1abw23UDdHPJxYDB7Yt6Fl7CLJmlFkbpDqEjtm7XlJU2VqF324iUpbQVZQ4arxZzFKwTy9qShyj244Zx1sZBTgOKr79rqwacA22f7PemYZDqexnH-l3JJ9nqiFnIILn-sJrMzKvw2VlnerE4KN9dhhnJX8iudPY1GjY5L3GA-r0djmfdxmZBGib0jrGTeN0pNVBveXoegpXmSAUk1GqwJvI",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAxGLiOQm0E1GKAkXRnvT3wwhbpd-EuejhaKWTDvgO8lzcHkrw7ilNXEhk2Vh6pTgaTxNIaFGI5bpbK3PJ2JuyKWtyWirvTafF6eKeF2YIquW_rIuTYbLjNteYEqB-5QVgfaNjM1-Ly_eHIHk5Y3H7bxlLB4Byk7STc1-MXkSRolC2tkXCXlsv8hefcLHeqwfoTNcrbJCff_fyj53hmp87NTIqzQ-EAYp1CE2z5BVX-ug3ThGs67MYNBilE7elUGHZPNKw_0YLZI9k",
    ],
    category: "Bridal",
    categorySlug: "bridal-couture",
    collection: "Heritage & Harmony",
    fabric: "Silk Organza",
    colors: [
      { name: "Gold Blue", hex: "#4169E1" },
    ],
    sizes: [
      { name: "XS", available: true },
      { name: "S", available: true },
      { name: "M", available: true },
      { name: "L", available: true },
      { name: "XL", available: true },
    ],
    stock: 5,
    rating: 5.0,
    reviewCount: 28,
    features: ["Premium silk organza", "Heavy embroidery", "Bridal quality"],
    modelInfo: "Model is 5'8\" wearing size M",
  },
  {
    id: "11",
    name: "Embroidered Lawn Suit",
    slug: "embroidered-lawn-suit",
    description: "Comfortable lawn suit with beautiful embroidery, perfect for everyday elegance.",
    price: 8500,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAxGLiOQm0E1GKAkXRnvT3wwhbpd-EuejhaKWTDvgO8lzcHkrw7ilNXEhk2Vh6pTgaTxNIaFGI5bpbK3PJ2JuyKWtyWirvTafF6eKeF2YIquW_rIuTYbLjNteYEqB-5QVgfaNjM1-Ly_eHIHk5Y3H7bxlLB4Byk7STc1-MXkSRolC2tkXCXlsv8hefcLHeqwfoTNcrbJCff_fyj53hmp87NTIqzQ-EAYp1CE2z5BVX-ug3ThGs67MYNBilE7elUGHZPNKw_0YLZI9k",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCZgQemWTJYcNGbQ1CLiUieXl88zu7SuUFGzsf5Gv-aNQWfwjf3C2dp_sh7LAldJT9SN7y1vEA-Wa43JxqvubIBkZYKYpXGERXs3qbHsYGEbC9IStdlrJ8dRcJXLMHC8xcgKfdXfoxl1i-l_ZPvav9_A_c-YCm2efOSDOvUxjLn9oIe1Y-3d9fEgDMPbWDqfsCJ4jS0-a1uQaP1WVvmarV_7ZPp3EulU_gVdgG6uDEvYlFRvGG_nsfiwd0zlNe9Obu1dg8s9Tj0Htc",
    ],
    category: "Casual",
    categorySlug: "pret",
    fabric: "Lawn",
    colors: [
      { name: "Ivory", hex: "#FFFFF0" },
      { name: "Sky Blue", hex: "#87CEEB" },
    ],
    sizes: [
      { name: "XS", available: true },
      { name: "S", available: true },
      { name: "M", available: true },
      { name: "L", available: true },
      { name: "XL", available: true },
    ],
    stock: 50,
    rating: 4.5,
    reviewCount: 234,
    features: ["Premium lawn", "Machine washable", "Comfortable fit"],
  },
  {
    id: "12",
    name: "Digital Silk Tunic",
    slug: "digital-silk-tunic",
    description: "Modern digital print silk tunic with contemporary design elements.",
    price: 12000,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCN9sRxqEiEvfwUQz8K5WQ5OqfKfAdQaCeIWGTs9F34YA9tJhoMO7AB1abw23UDdHPJxYDB7Yt6Fl7CLJmlFkbpDqEjtm7XlJU2VqF324iUpbQVZQ4arxZzFKwTy9qShyj244Zx1sZBTgOKr79rqwacA22f7PemYZDqexnH-l3JJ9nqiFnIILn-sJrMzKvw2VlnerE4KN9dhhnJX8iudPY1GjY5L3GA-r0djmfdxmZBGib0jrGTeN0pNVBveXoegpXmSAUk1GqwJvI",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCZgQemWTJYcNGbQ1CLiUieXl88zu7SuUFGzsf5Gv-aNQWfwjf3C2dp_sh7LAldJT9SN7y1vEA-Wa43JxqvubIBkZYKYpXGERXs3qbHsYGEbC9IStdlrJ8dRcJXLMHC8xcgKfdXfoxl1i-l_ZPvav9_A_c-YCm2efOSDOvUxjLn9oIe1Y-3d9fEgDMPbWDqfsCJ4jS0-a1uQaP1WVvmarV_7ZPp3EulU_gVdgG6uDEvYlFRvGG_nsfiwd0zlNe9Obu1dg8s9Tj0Htc",
    ],
    category: "Contemporary",
    categorySlug: "pret",
    fabric: "Silk",
    colors: [
      { name: "Emerald", hex: "#2D5F2D" },
      { name: "Coral", hex: "#FF7F50" },
    ],
    sizes: [
      { name: "XS", available: false },
      { name: "S", available: true },
      { name: "M", available: true },
      { name: "L", available: true },
      { name: "XL", available: false },
    ],
    stock: 18,
    rating: 4.6,
    reviewCount: 87,
    features: ["Digital print", "Pure silk", "Modern cut"],
  },
];

export const REVIEWS: Review[] = [
  {
    id: "1",
    productId: "2",
    customerName: "Sara Ahmed",
    customerLocation: "Karachi",
    rating: 5,
    title: "Absolutely stunning!",
    content: "I ordered this for my sister's wedding and I am blown away by the quality. The embroidery is exactly as shown in the pictures, maybe even better. The fabric is very soft and premium. Fits perfectly too!",
    date: "2024-12-15",
    verified: true,
    images: ["https://lh3.googleusercontent.com/aida-public/AB6AXuCZgQemWTJYcNGbQ1CLiUieXl88zu7SuUFGzsf5Gv-aNQWfwjf3C2dp_sh7LAldJT9SN7y1vEA-Wa43JxqvubIBkZYKYpXGERXs3qbHsYGEbC9IStdlrJ8dRcJXLMHC8xcgKfdXfoxl1i-l_ZPvav9_A_c-YCm2efOSDOvUxjLn9oIe1Y-3d9fEgDMPbWDqfsCJ4jS0-a1uQaP1WVvmarV_7ZPp3EulU_gVdgG6uDEvYlFRvGG_nsfiwd0zlNe9Obu1dg8s9Tj0Htc"],
    helpful: 12,
  },
  {
    id: "2",
    productId: "2",
    customerName: "Maha Khan",
    customerLocation: "Lahore",
    rating: 4,
    title: "Good quality but delivery was late",
    content: "The suit itself is beautiful, very elegant color. However, the delivery took 2 days longer than expected. Customer service was responsive though.",
    date: "2024-12-10",
    verified: true,
    helpful: 4,
  },
  {
    id: "3",
    productId: "1",
    customerName: "Fatima Khan",
    customerLocation: "Lahore",
    rating: 5,
    title: "Ordering online was a breeze",
    content: "The COD option gave me peace of mind, and the packaging was so luxurious. Truly a premium experience.",
    date: "2024-12-08",
    verified: true,
    helpful: 8,
  },
  {
    id: "4",
    productId: "1",
    customerName: "Zainab Malik",
    customerLocation: "Islamabad",
    rating: 5,
    title: "Been shopping from MALA's store for years",
    content: "So happy they are finally online! The unstitched collection is just as vibrant as in the photos.",
    date: "2024-12-05",
    verified: true,
    helpful: 15,
  },
  {
    id: "5",
    productId: "5",
    customerName: "Ayesha Siddiqui",
    customerLocation: "Rawalpindi",
    rating: 5,
    title: "Worth every rupee!",
    content: "The velvet quality is exceptional. Got so many compliments at the wedding. Will definitely order again!",
    date: "2024-12-01",
    verified: true,
    helpful: 22,
  },
];

export const FEATURED_REVIEWS = REVIEWS.slice(0, 3);

export const SHIPPING_OPTIONS: ShippingOption[] = [
  {
    id: "standard",
    name: "Standard Delivery",
    description: "Delivered within 3-5 business days",
    price: 0,
    estimatedDays: "3-5 days",
  },
  {
    id: "express",
    name: "Express Delivery",
    description: "Delivered within 1-2 business days",
    price: 200,
    estimatedDays: "1-2 days",
  },
  {
    id: "same-day",
    name: "Same Day Delivery",
    description: "Available in Karachi, Lahore & Islamabad only",
    price: 500,
    estimatedDays: "Same day",
  },
];

export const PAKISTAN_CITIES = [
  "Karachi",
  "Lahore",
  "Islamabad",
  "Rawalpindi",
  "Faisalabad",
  "Multan",
  "Peshawar",
  "Quetta",
  "Sialkot",
  "Gujranwala",
  "Hyderabad",
  "Nowshera",
  "Abbottabad",
  "Bahawalpur",
  "Sargodha",
];

export const PAKISTAN_PROVINCES = [
  "Punjab",
  "Sindh",
  "Khyber Pakhtunkhwa",
  "Balochistan",
  "Islamabad Capital Territory",
  "Azad Kashmir",
  "Gilgit-Baltistan",
];

export const FABRIC_TYPES = [
  "Chiffon",
  "Velvet",
  "Silk",
  "Organza",
  "Lawn",
  "Cotton",
  "Net",
  "Jacquard",
];

export const TRUST_BADGES = [
  {
    icon: "Award",
    title: "30 Years Heritage",
    description: "Established 1994",
  },
  {
    icon: "Truck",
    title: "Free Shipping",
    description: "Across Pakistan",
  },
  {
    icon: "CreditCard",
    title: "Cash on Delivery",
    description: "Pay when you receive",
  },
  {
    icon: "RotateCcw",
    title: "Easy Returns",
    description: "7-day hassle-free",
  },
];

// Hero Image
export const HERO_IMAGE = "https://lh3.googleusercontent.com/aida-public/AB6AXuC3j_QvoitUf83vneovI1Ik894vPMb-uSJUU53gTrUkeWEzKgsNYC52dFUd8FMwU-r_ycfWbn2yJOCGgR8kM7cgl3BHw8JV7LvSpydCEqfodd0axzpBLL5iuAxw__faHxdHKExiguBmnoxZrbbpCyRP-IQ-ZN1WR5N2WOgyiTDVCXQknybYpCdsJV3z28v9zZSv41VOFfnHd7MJ3XrNtHa-KP3BHGW6_uUWogUTpPzWoPc7d5PIpUbm02lh-axsIU0EUoKKDad4Ggg";
